### ISSUE TITLE
can't install plugin

### ISSUE THREAD

**Issue by janwillemCA** [meteostat/meteostat-grafana#9]
when trying install the plugin with: grafana-cli plugins install meteostat-meteostat-datasource

im getting a 404 error: Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

how can this be solved?

**Comment by Kkoile** [comment]
Hi @janwillemCA 
thanks for reporting the issue. The problem is that the currently released version 0.1.5 is only compatible for grafana v7.3.*
It seems that grafana lacks of a good error message here, that the plugin is not missing, but the versions are not compatible. When starting a grafana instance with version 7.3.* you can install the plugin.

We are already  in the process of publishing a new version of our plugin, which is compatible with grafana versions 7.5*. Unfortunately it always takes a long time to release a new version.
See the pull request for publishing our new version https://github.com/grafana/grafana-plugin-repository/pull/942
